apiVersion: v1
kind: Service
metadata:
  name: jobmanager
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "6123"
      port: 6123
      targetPort: 6123
  selector:
    app: jobmanager
status:
  loadBalancer: {}
