apiVersion: v1
kind: Service
metadata:
  name: pinpoint-hbase
spec:
  ports:
    - name: "60000"
      port: 60000
      targetPort: 60000
    - name: "16010"
      port: 16010
      targetPort: 16010
    - name: "60020"
      port: 60020
      targetPort: 60020
    - name: "16030"
      port: 16030
      targetPort: 16030
  selector:
    app: pinpoint-hbase
status:
  loadBalancer: {}
